In [25]:
import torch
import numpy as np

### 通过numpy来创建Tensor

方法：torch.from_numoy(numpy数组)

In [26]:
data1 = np.array([1,2,3])

In [27]:
torch.from_numpy(data1)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
data2 = np.ones([2,3])

In [29]:
torch.from_numpy(data2)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### 从List里导入数据创建Tensor

方法：torch.tensor(数据)

In [30]:
torch.tensor([[2.,3.2],[4,5]])

tensor([[2.0000, 3.2000],
        [4.0000, 5.0000]])

注意区别torch.tensor()和torch.Tensor()

tensor()括号里接收的是list，是现成的数据 

Tensor()接收的是shape，是数据的维度

In [31]:
torch.Tensor(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 创建不初始化的Tensor

方法：

1.torch.empty(shape)

2.torch.FloatTensor(shape)

3.torch.IntTensor(shape)

.......

In [34]:
torch.FloatTensor(1,2,3)

tensor([[[2.5961e+20, 2.5206e-09, 2.6728e+23],
         [2.0431e+20, 4.1199e-11, 7.1450e+31]]])

In [44]:
torch.IntTensor(1,2,3)

tensor([[[0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [45]:
torch.empty(1,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

### 如果不指定Tensor类型，一般情况下都是FloatTensor

1.使用.type()方法查看数据的类型

2.使用torch.set_default_tensor_type(要更改的数据类型)方法更改默认数据类型

In [46]:
torch.Tensor(1,2,3).type()

'torch.FloatTensor'

特殊情况下，需要将默认数据类型更改为其他类型，方法如下：

In [47]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [48]:
torch.Tensor(1,2,3).type()

'torch.DoubleTensor'

In [49]:
torch.set_default_tensor_type(torch.FloatTensor)

### 一些特殊初始化

##### 一、均匀分布初始化：

1.[0,1]之间：torch.rand(shape)

2.[0,1]之间：torch.rand_like(Tensor类型数据)

3.自定义区间[min,max)之间：torch.randint(min.max,[shape])

In [55]:
data5 = torch.rand(3,3)
data5

tensor([[0.2527, 0.2670, 0.4471],
        [0.4228, 0.8117, 0.2410],
        [0.1184, 0.7893, 0.8695]])

In [56]:
#这里是导入一个Tensor类型数据，方法会读取此数据的shape，并利用torch.rand()方法生成一个和此数据相同维度的随机Tensor
torch.rand_like(data5)

tensor([[0.0899, 0.4156, 0.3830],
        [0.8078, 0.4536, 0.9427],
        [0.9739, 0.1622, 0.8116]])

In [57]:
#区间为[1,10)，也就是说，取随机值的区间包括min，但不包括max
#此处的维度是作为一个整体来输入，故应该输入一个list，即用[]括起来
torch.randint(1,10,[3,3])

tensor([[3, 3, 6],
        [8, 3, 6],
        [7, 8, 2]])

##### 二、正态分布初始化：

1.标准正态分布：torch.randn(3,3)

In [58]:
torch.randn(3,3)

tensor([[ 1.0454, -1.3279, -1.3810],
        [-1.0127,  1.2586,  0.4997],
        [ 1.2610,  0.5073, -1.4066]])

##### 三、初始化为Tensor内数据完全相同

1.初始化为全是num：torch.full([shape],num)

2.初始化为全是0：torch.zeros(shape)

3.初始化为全是0：torch.ones(shape) 或 torch.ones_like(Tensor)

In [59]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [62]:
#此处注意如果只写[]会生成一个标量，即数字，而不是向量
torch.full([],7)

tensor(7)

In [63]:
torch.full([1],7)

tensor([7])

In [71]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [72]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [77]:
torch.ones_like(data5)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##### 四、生成等差数列

1.在[min,max)上生成等差数列：torch.arange(min.max)

2.在[min,max)上生成间隔为n的等差数列：torch.arange(min.max,n)

3.在[min,max]上生成s等分的等差数列：torch.linspace(min,max,s)

4.在[10^min,10^max]上生成s等分的等差数列：torch.logspace(min,max,s)

In [65]:
#注意此处不包含10
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [69]:
#此处包括10
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [70]:
#此处包括max^10
torch.logspace(0,-1,10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

##### 四、生成主对角为1的对角矩阵

1.torch.eye(shape)

2.torch.eye_like(Tensor)

In [73]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [74]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])