In [2]:
import torch

In [3]:
data1 = torch.rand(4,1,28,28)

In [4]:
data1.shape

torch.Size([4, 1, 28, 28])

### 重新改变维度

.view(维度):只要变换前和变换后各维度的总乘积相等，就可以随意变换，否则报错

In [5]:
data1.view(28,4,28).shape

torch.Size([28, 4, 28])

In [6]:
data1.view(7,2,2,2,2,28).shape

torch.Size([7, 2, 2, 2, 2, 28])

### 增加维度

.unsqueeze(索引号)：在指定索引位置插入一个新维度

插入一个维度并不改变数据本身，只是改变了数据的理解方式，从而便于以后增加我们需要的数据

In [8]:
#在0位置插入一个新维度，其余维度往后稍稍
data1.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [10]:
#在-1位置插入一个新维度，其余维度往前挤挤
data1.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [12]:
#在2位置处插入一个新维度，其余维度往两边靠靠
data1.unsqueeze(2).shape

torch.Size([4, 1, 1, 28, 28])

In [13]:
data1.unsqueeze(-3).shape

torch.Size([4, 1, 1, 28, 28])

In [14]:
data2 = torch.tensor([1,2])

插入维度在不同位置，Tensor的结构变化不同，注意以下两个的区别：

In [16]:
data2.unsqueeze(0)

tensor([[1, 2]])

In [17]:
data2.unsqueeze(-1)

tensor([[1],
        [2]])

### 挤压维度

.squeeze(索引号)：在指定索引位置删除维度

只有值为1的维度才能被挤压（删除），因为挤压维度操作不能改变数据量，只能改变数据的结构

这里如果不指定索引号，程序会自动把能删除的（值为1的维度）全部删除

如果指定的索引值的维度的数值不为1，则即使执行代码也不会删除该维度，只会原封不动返回

In [27]:
data3 = torch.randn(4,1,1,1,3)

In [28]:
data3.shape

torch.Size([4, 1, 1, 1, 3])

In [35]:
#没指定索引，把所有值为1的维度全部挤压删除
data3.squeeze().shape

torch.Size([4, 3])

In [30]:
data3.squeeze(1).shape

torch.Size([4, 1, 1, 3])

In [31]:
data3.squeeze(1).squeeze(1).shape

torch.Size([4, 1, 3])

In [37]:
#指定索引的维度的值不为1，如果挤压则会破坏数据，故原封不动返回
data3.squeeze(0).shape

torch.Size([4, 1, 1, 1, 3])

In [38]:
data3.squeeze(-1).shape

torch.Size([4, 1, 1, 1, 3])

### 关于矩阵转置

.t()

只能是维度为2的矩阵才可以，1,3,....维的无法进行转置，会报错

In [43]:
data4 = torch.randn(3,4)
data4

tensor([[ 0.6513,  1.1311, -1.6670,  0.4014],
        [-0.3213,  0.2807, -0.0095, -0.2634],
        [ 1.7182, -0.1083, -0.6492, -0.1958]])

In [44]:
data4.t()

tensor([[ 0.6513, -0.3213,  1.7182],
        [ 1.1311,  0.2807, -0.1083],
        [-1.6670, -0.0095, -0.6492],
        [ 0.4014, -0.2634, -0.1958]])

In [47]:
#data3维度>2，所以不能转置，报错
data3.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 5D

### 维度扩展

.expand()：进行维度扩展，但不增加数据（推荐：速度快、节省内存空间）

.repeat()：扩展维度之后将原有的数据经过复制赋给新扩展出来的空余位置

只有指定维度原来值为1，变成N，才是可行的，M变成N会报错！！！

括号中不想改变的维度对应位置写-1即可，如:.expand(-1,-1,-1,5,-1)

In [49]:
data3.shape

torch.Size([4, 1, 1, 1, 3])

In [50]:
data3.expand(4,2,3,4,3).shape

torch.Size([4, 2, 3, 4, 3])

In [53]:
#第0个维度原来的值不是1，却要变成个10，转换不了，报错
data3.expand(10,1,1,1,3)

RuntimeError: The expanded size of the tensor (10) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [10, 1, 1, 1, 3].  Tensor sizes: [4, 1, 1, 1, 3]

In [57]:
#除了2位置，其他都不想改变，于是全写成-1
data3.expand(-1,-1,6,-1,-1).shape

torch.Size([4, 1, 6, 1, 3])

### 交换两个维度

.transpose(a1,a2)交换索引号为a1和a2的两个维度

In [68]:
data1.shape

torch.Size([4, 1, 28, 28])

In [78]:
#交换1,3位置的两个维度
data1.transpose(1,3).shape

torch.Size([4, 28, 28, 1])

In [81]:
#先交换1,3维度
#再变成4*784的张量
#再变回4*1*28*28的张量
#这里报错的原因是：维度变换后数据就不连续了，需要contiguous()方法来使数据恢复连续
data1.transpose(1,3).view(4,28*28*1).view(4,1,28,28).shape

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [86]:
#使用contiguous()方法使数据恢复连续后便不报错了
A1 = data1.transpose(1,3).contiguous().view(4,28*28*1).view(4,1,28,28)
A1.shape

torch.Size([4, 1, 28, 28])

In [88]:
A2 = data1.transpose(1,3).contiguous().view(4,28*28*1).view(4,28,28,1).transpose(1,3)
A2.shape

torch.Size([4, 1, 28, 28])

上面A1和A2两个张量都是经过一系列维度变换最终再回到和变换前维度相同

但是，两个张量虽然维度和data1相同，但内部数据的顺序和结构上：A2和data1相同，A1不同

A1变化过程：
1. [B , C , H , W] -> \[B , W , H , C\] ([4,28,28,3])
2. [B , W , H , C] -> \[B , C\*W\*H] ([4,3\*28\*28])
    (C跑到前面去了,W往后顺延一位，导致跟data1的结构相比，W和H的位置前后互换了)
3. [B , C\*W\*H] -> [B , C , W , H]
    (最终结果是W和H位置是反的)
    
A2变化过程：
1. [B , C , H , W] -> \[B , W , H , C\] ([4,28,28,3])
2. [B , W , H , C] -> \[B , C\*W\*H] ([4,3\*28\*28])
3. [B , C\*W\*H] -> [B , W , H , C]
4. [B , W , H , C] -> [B , C , H , W] (跟原来完全一样了)

### 比较两张量是否相同
.eq(T1,T2):比较T1和T2两个shape相同的张量对应位置的值是否相同，相同记True，否则记False，返回一个同样大小的布尔型Tensor

In [91]:
torch.eq(data1,A1)

tensor([[[[ True, False, False,  ..., False, False, False],
          [False,  True, False,  ..., False, False, False],
          [False, False,  True,  ..., False, False, False],
          ...,
          [False, False, False,  ...,  True, False, False],
          [False, False, False,  ..., False,  True, False],
          [False, False, False,  ..., False, False,  True]]],


        [[[ True, False, False,  ..., False, False, False],
          [False,  True, False,  ..., False, False, False],
          [False, False,  True,  ..., False, False, False],
          ...,
          [False, False, False,  ...,  True, False, False],
          [False, False, False,  ..., False,  True, False],
          [False, False, False,  ..., False, False,  True]]],


        [[[ True, False, False,  ..., False, False, False],
          [False,  True, False,  ..., False, False, False],
          [False, False,  True,  ..., False, False, False],
          ...,
          [False, False, False,  ...,  True, Fa

In [93]:
#shape不同，不能比较，报错
torch.eq(data1,data4)

RuntimeError: The size of tensor a (28) must match the size of tensor b (4) at non-singleton dimension 3

##### all方法

如果张量中全是True，返回一个False的张量，否则返回True的张量

In [96]:
torch.all(torch.eq(data1,A1))

tensor(False)

In [97]:
torch.all(torch.eq(data1,A2))

tensor(True)

上面两个输出结果便能证明A1和A2的区别，虽然shape相同，但A1中的数据与data1不符，数据已经被污染了，A2则完美还原回了data1

### 按指定顺序重新排列各维度
.permute(索引1，索引2....)

In [99]:
data1.permute(2,1,0,3).shape

torch.Size([28, 1, 4, 28])