In [25]:
import torch

pytorch不支持string，如果想表示string必须自定义编码方式来实现

### 定义一个2*3的Tensor，内容随机

In [26]:
data1 = torch.randn(2,3)

### 检查Tensor变量类型的方法如下：

In [27]:
data1.type()

'torch.FloatTensor'

In [28]:
#此方法是python自带的，只能检测出基本的数据类型
type(data1)

torch.Tensor

In [29]:
#检验是否是指定数据类型，返回True或False
isinstance(a,torch.FloatTensor)

True

#### 通过.cuda()方法将CPU上的Tensor转化为GPU上的cuda.Tensor

In [30]:
isinstance(data1,torch.cuda.DoubleTensor)
data1 = data1.cuda()
isinstance(data1,torch.cuda.DoubleTensor)

AssertionError: Torch not compiled with CUDA enabled

### 定义标量：

In [31]:
torch.tensor(1.)

tensor(1.)

In [32]:
torch.tensor(1.3)

tensor(1.3000)

### 查看标量的形状的方法：

In [33]:
data2 = torch.tensor(2.2)

In [34]:
data2.shape

torch.Size([])

In [35]:
data2.size()

torch.Size([])

In [38]:
len(data2.shape)

0

In [84]:
#返回张量的维度
data2.dim()

0

### 向量初始化方法：

1.直接赋值：

In [39]:
torch.tensor([1.1])

tensor([1.1000])

In [40]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

2.指定尺寸，随机赋值

In [46]:
#这里括号里并没写[]只是写了数字，则数字代表向量的尺寸
#向量中的数值是随机的
torch.FloatTensor(1)

tensor([1.8331e-40])

In [45]:
torch.FloatTensor(3)

tensor([1.8331e-40,        nan, 1.1210e-44])

3.利用numpy建立数组，生成Tensor向量

In [51]:
import numpy as np
data3 = np.ones(2)
data3

array([1., 1.])

In [52]:
torch.from_numpy(data3)

tensor([1., 1.], dtype=torch.float64)

### n*m型的张量:

In [70]:
data4 = torch.randn(2,3)
data4

tensor([[ 0.4220, -1.1960, -0.5188],
        [-1.2680,  1.1803, -0.0880]])

In [55]:
data4.shape

torch.Size([2, 3])

In [58]:
data4.size()

torch.Size([2, 3])

In [59]:
data4.size(0)

2

In [60]:
data4.size(1)

3

In [63]:
data4.shape[0]

2

In [64]:
data4.shape[1]

3

### 多维张量:

In [73]:
data5 = torch.randn(1,2,3)
data5

tensor([[[ 0.4519,  1.0325,  1.9760],
         [-0.0180,  0.2264,  1.2355]]])

In [74]:
data5.shape

torch.Size([1, 2, 3])

In [77]:
data5[0]

tensor([[ 0.4519,  1.0325,  1.9760],
        [-0.0180,  0.2264,  1.2355]])

In [79]:
list(data5.shape)

[1, 2, 3]

### 查询张量占的内存大小：

In [83]:
data6 = torch.randn(2,3,28,28)
data6.numel()
#2*3*28*28 = 4704

4704