### 索引

In [10]:
import torch

In [30]:
data1 = torch.rand(4,2,28,28)

In [12]:
data1[0].shape

torch.Size([2, 28, 28])

In [13]:
data1[0,0].shape

torch.Size([28, 28])

In [14]:
data1[0,0,25]

tensor([0.3767, 0.9639, 0.7762, 0.9524, 0.1435, 0.3979, 0.9808, 0.1397, 0.6636,
        0.9424, 0.8356, 0.7930, 0.1745, 0.7552, 0.3382, 0.3451, 0.4895, 0.6145,
        0.9372, 0.2517, 0.2337, 0.9459, 0.6694, 0.2189, 0.3714, 0.8450, 0.2381,
        0.5170])

In [15]:
data1[0,0,1,2]

tensor(0.1642)

### 取连续的一部分

In [16]:
data1.shape

torch.Size([4, 2, 28, 28])

取第一个维度在2之前的部分（不包括2）（:数字）

In [20]:
data1[:2].shape

torch.Size([2, 2, 28, 28])

和上面同理

In [21]:
data1[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

取第一个维度在2以及2之后的部分（包括2）（数字:）

In [23]:
data1[:2,1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [24]:
#-1，-2，-3依次表示倒数第一个，倒数第二个....
#所以这里 -1： 表示只有最后一个
data1[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

### 有间隔的选取

In [27]:
#0:28:2表示从0位置到28位置（不包括28）每隔2个取一个
#0::2表示从0开始到最后每隔2个取一个
data1[:,:,0:28:2,0::2].shape

torch.Size([4, 2, 14, 14])

::1 和 : 等价

### 根据索引号精确选取

.index_select(维度序号，Tensor类型选取的索引编号列表)

In [39]:
#特别需要注意！！！！！
#这里的第二个参数必须是Tensor类型的，所以列表必须转换成IntTensor类型，否则报错
data1.index_select(0,torch.IntTensor([1,2])).shape

torch.Size([2, 2, 28, 28])

In [42]:
#复习一下torch.arange(min,max,n)表示在[min.max)上取公差为n的等差数列
#torch.arange(5)表示取[0,4]
data1.index_select(2,torch.arange(5)).shape

torch.Size([4, 2, 5, 28])

### 关于“...”符号

...符号表示全都要

In [45]:
#只有...表示全都要
data1[...].shape

torch.Size([4, 2, 28, 28])

In [47]:
#[0,...]表示第一个维度取第0个，剩下三个维度全要
data1[0,...].shape

torch.Size([2, 28, 28])

In [49]:
#第一个维度全都要
#第二个维度取0及其后面的
#第三个维度在[13,23]之间隔2个取一个
#剩下的维度全都要
data1[:,0:,13:23:2,...].shape

torch.Size([4, 2, 5, 28])

In [50]:
data1[...,:2].shape

torch.Size([4, 2, 28, 2])

### 用masked_select方法选取符合条件的元素

In [52]:
data2 = torch.randn(3,4)
data2

tensor([[ 0.7098, -1.1831,  0.7865,  0.2862],
        [-0.1751,  0.3652,  0.0164,  0.0825],
        [ 1.1699,  0.3092,  0.2292, -1.7656]])

data.ge(num)方法表示创建与data同形的矩阵，并将>=num的元素对应位置置为True，其他置False

作用就是取出>=num的元素

In [54]:
mask = data2.ge(0.5)
mask

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [ True, False, False, False]])

torch.masked_select(data,mask)：

输入data和data同形的Bool类型张量，筛出True的值

In [58]:
#输入data和data同形的Bool类型张量，筛出True的值
torch.masked_select(data2,mask)

tensor([0.7098, 0.7865, 1.1699])

### 将张量打平成一维向量，再用打平之后的索引选取

torch.take(数据,tensor列表)

In [61]:
data3 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
data3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
torch.take(data3,torch.tensor([0,2,4,6,8]))

tensor([1, 3, 5, 7, 9])